# Documentation à propos de cette page : https://fshschool.org/docs/sushi/configuration/

id: ans.hl7v2.fr.teleradiologie
canonical: https://interop.esante.gouv.fr/ig/hl7v2/teleradiologie # the last part of canonical and id must be the same
name: CISIS_TLR_HL7_V2 # Should be an acronym
title: Volet Téléradiologie
publisher:
  name: Agence du Numérique en Santé (ANS) - 2-10 Rue d'Oradour-sur-Glane, 75015 Paris
  url: https://esante.gouv.fr
status: draft
version: 0.1.0 # shall conforms to Semantic Versioning https://fr.wiktionary.org/wiki/SemVer
fhirVersion: 4.0.1
copyrightYear: 2020+
releaseLabel: ci-build # le release label doit être conforme au cycle de vie de la doctrine du ci-sis
jurisdiction: urn:iso:std:iso:3166#FR "FRANCE"

parameters: #Parameters list - https://build.fhir.org/ig/FHIR/fhir-tools-ig/CodeSystem-ig-parameters.html
    shownav: 'true'



pages:
    index.md:
        title: Accueil
    specifications_fonctionnelles.md:
        title: "Volume 1 : Etude fonctionnelle"
    norme_standard.md:
        title: Normes et Standards
    specifications_techniques.md:
        title: "Volume 2 : Détail des transactions"
    diag_sequence.md:
        title: Diagramme de séquence - Spécification technique
    table_obs.md:
        title: Table TLR_OBSERVATION
    table_orga.md:
        title: Table TLR_TYPE_ORGANISATION
    sub-id.md:
        title: Utilisation du champ OBX-4 – Observation Sub-ID
    exemples.md:
        title: Exemples de messages
    doc-ref.md:
        title: Références documentaires
    change-log.md:
        title: Historique des versions
    tests.md:
        title: Test
    downloads.md:
        title: Téléchargements
menu:
    Accueil: index.html
    Volume 1 - Etude fonctionnelle: 
        "Méthode": specifications_fonctionnelles.html#méthode
        "Cadre juridique et orientations organisationnelles": specifications_fonctionnelles.html#cadre-juridique-et-orientations-organisationnelles
        "Organisation du contexte métier": specifications_fonctionnelles.html#organisation-du-contexte-métier
        "Définition des processus colllaboratifs": specifications_fonctionnelles.html#définition-des-processus-collaboratifs
        "Description des processus collaboratifs et identification des flux": specifications_fonctionnelles.html#description-des-processus-collaboratifs-et-identification-des-flux
        "Identification des concepts véhiculés dans les flux": specifications_fonctionnelles.html#identification-des-concepts-véhiculés-dans-les-flux-dinformations-et-correspondance-avec-les-classes-et-attributs-du-mos
        "Modélisation des flux d’informations": specifications_fonctionnelles.html#modélisation-des-flux-dinformations
    Volume 2 – Détail des Transactions: specifications_techniques.html
    Volume 3 - Annexes:
        Normes et Standards: norme_standard.html
        Diagramme de séquence - Spécification technique: diag_sequence.html
        Utilisation du champ OBX-4 – Observation Sub-ID: sub-id.html
        Table TLR_OBSERVATION: table_obs.html
        Table TLR_TYPE_ORGANISATION: table_orga.html
        Exemples de messages: exemples.html
        Références documentaires: doc-ref.html
    Test: tests.html
    Historique des versions: change-log.html
    Téléchargements: downloads.html
